baseURL = "/"
languageCode = "en-us"
title = "Nik's Data Blog"
#git submodule add https://github.com/vaga/hugo-theme-m10c
theme="hugo-theme-m10c"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "\\.Rproj.user"]

[params]
  author = "Nik Seldon"
  description = "I am physicist and self taught programmer with a strong passion for analyzing and modeling data, understanding pattern within it and applying scientific methods. In this Blog I want to write down some of my work and thoughts just to keep track of it and potentially, help interested with their work."

  [[params.social]]
    name = "github"
    url = "https://github.com/gohugoio"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/gohugoio"
    #[[params.social]]
    #name="googlescholar"
    #url = "https://scholar.google.com/citations?hl=en&user=CbflQAsAAAAJ&view_op=list_works&sortby=pubdate"

  darkestColor = "#d35050"
  darkColor = "#212121"
  lightColor = "#f5e3e0"
  lightestColor = "#f5f5f5"
  primaryColor = "#fff"